# git clone https://github.com/dexpota/kitty-themes.git ~/.config/kitty/kitty-themes
include ./kitty-themes/themes/OneDark.conf

font_family       Maple Mono NL SL NF CN
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         11.0
